package java_solutions;

import java.math.BigInteger;
import java.util.ArrayList;

public class p029 {

	public static final int A_MAX = 100;
	public static final int B_MAX = 100;
	
	public static void main(String[] args) {
		
		ArrayList<BigInteger> nums = new ArrayList<BigInteger>();
		int ans;

		BigInteger temp;
		for(int a=2; a<=A_MAX; a++){
			for(int b=2; b<=B_MAX; b++){
				temp = new BigInteger(a + "").pow(b);
				if(!contains(nums, temp))
					nums.add(temp);
			}
		}
		
		
		// This function doesn't work but if it did, it'd be more effecient
		// than the if statement with the home made contains function above
		//nums = makeArrayListDistinct(nums);
		
		ans = nums.size();
		
		System.out.println("There are " + ans + " distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100");
		
	}

	public static ArrayList<BigInteger> makeArrayListDistinct(ArrayList<BigInteger> nums){
		BigInteger temp;
		
		for(int i=0; i<nums.size(); i++){
			temp = nums.get(i);
			for(int j=i+1; j<nums.size(); j++){
				if(temp.equals(nums.get(j)))
					nums.remove(nums.get(j));
			}
		}
		
		return nums;
	}
	
	public static boolean contains(ArrayList<BigInteger> nums, BigInteger big){
		for(int i=0; i<nums.size(); i++){
			if(nums.get(i).equals(big))
				return true;
		}
		return false;
	}
	
}
